### ISSUE TITLE
Unable to build with msvc.

### ISSUE THREAD

**Issue by Lucas-Marcel** [OGRECave/ogre#3214] opened 2024-09-06 02:17 UTC
#### System Information
- Operating System / Platform: Windows 10
- Ogre Version: :ogre-14.2.6-
- RenderSystem: :GLES2, D3D11, GL, GL3PLUS

-- I'm trying to build Ogre with visual studio, but i'm getting a lot of errors. A few days ago (less than one week) i could build it with no issues --

#### Ogre.log
<!
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(Version.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(Version.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(Importer.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(Importer.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(MaterialSystem.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(MaterialSystem.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(scene.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(scene.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(DefaultLogger.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(DefaultLogger.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(DefaultIOSystem.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(DefaultIOSystem.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(IOSystem.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(IOSystem.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(BaseProcess.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(BaseProcess.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(ScenePreprocessor.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(ScenePreprocessor.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(BaseImporter.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(BaseImporter.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(ValidateDataStructure.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(ValidateDataStructure.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(ImporterRegistry.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(ImporterRegistry.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(PostStepRegistry.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(PostStepRegistry.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(Exceptional.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(Exceptional.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(DefaultIOStream.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(DefaultIOStream.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(material.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(material.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(XFileImporter.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(XFileImporter.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(AMFImporter.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(AMFImporter.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(3DSLoader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(3DSLoader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(MD3Loader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(MD3Loader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(MDLLoader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(MDLLoader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(MD2Loader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(MD2Loader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(PlyLoader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(PlyLoader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(ASELoader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(ASELoader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(ObjFileImporter.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(ObjFileImporter.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(HMPLoader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(HMPLoader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(SMDLoader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(SMDLoader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(MDCLoader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(MDCLoader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(MD5Loader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(MD5Loader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(STLLoader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(STLLoader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(LWOLoader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(LWOLoader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(DXFLoader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(DXFLoader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(NFFLoader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(NFFLoader.obj)	1		
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssimpLoader.obj	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\assimp-vc143-mt.lib(RawLoader.obj)	1		
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value ...
.......................................................... COULDN'T POST THE WHOLE ERROR, I PICKED WHAT I THINK ARE THE MOST IMPORTANT ONES.......................................

		
Warning	LNK4098	defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\PlugIns\Assimp\LINK	1		
Error	LNK1319	364 mismatches detected	Codec_Assimp	F:\DEVELOPMENT_LIBRARIES\ogre-14.2.6\msvcBuild\bin\Debug\Codec_Assimp_d.dll	1		

```
-->

**Comment by paroj** [comment] 2024-09-06 05:57
duplicate of #1303

**Closed by paroj** 2024-09-06 05:57 UTC
