### ISSUE TITLE
Android crash on library initialisation

### ISSUE THREAD

**Issue by arkeon7** [OGRECave/ogre#734] opened 2018-04-17 12:04 UTC
#### System Information
- Ogre Version: 1.11
- Operating System / Platform: Android
- RenderSystem: GLSLES2

#### Detailled description
I use NDK r15c GCC 4.9
When the library containing Ogre is loaded, it crash on memory allocation.
Debugger pass through: 
Light PerPixelLighting::msBlankLight; in OgreShaderExPerPixelLighting.cpp
MovableObject::MovableObject() : MovableObject(BLANKSTRING) {} in OgreMovableObject.cpp
template<int Category = MEMCATEGORY_GENERAL> class AllocatedObject {};
and crash in basic_string.tcc
```
template<typename _CharT, typename _Traits, typename _Alloc>
    basic_string<_CharT, _Traits, _Alloc>::
    basic_string(const basic_string& __str)
    : _M_dataplus(__str._M_rep()->_M_grab(_Alloc(__str.get_allocator()),
					  __str.get_allocator()),
		  __str.get_allocator())
    { }
```
Maybe it's related to the OgreMemoryAllocatorConfig.h changes ?
I have no idea where to look at ^^
#### Log
```
04-17 14:04:04.813 11326 11425 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xfffffffc in tid 11425 (Thread-3)
```

**Comment by arkeon7** [comment] 2018-04-18 14:08
tried to rebuild all with android-ndk-r14b, still the same crash...
I'll try to get back to r10e... but last time I got some trouble to build Ogre with it.

**Comment by arkeon7** [comment] 2018-04-20 14:43
the same with NDK r10e...
still no clue any idea ?
What android toolchain do you use for android build ? did you tried it in static linking ?

**Comment by paroj** [comment] 2018-04-21 16:55
the CI uses `r15c`. On android only static linking is used.

Can you try a clean build/ OGRE_ENABLE_PRECOMPILED_HEADERS=OFF?

**Comment by arkeon7** [comment] 2018-04-23 07:50
OGRE_ENABLE_PRECOMPILED_HEADERS is already OFF;
When it's ON the GCC compiler crash ^^

```
Scanning dependencies of target OgreMain_pch_dephelp
[ 41%] Building CXX object Ogre/Sources/OgreMain/CMakeFiles/OgreMain_pch_dephelp.dir/OgreMain_pch_dephelp.cxx.o
[ 41%] Linking CXX static library libOgreMain_pch_dephelp.a
[ 41%] Built target OgreMain_pch_dephelp
Scanning dependencies of target pch_Generate_OgreMain
[ 41%] Generating OgreStableHeaders.h.gch/OgreMain_Release.gch
[ 41%] Built target pch_Generate_OgreMain
Scanning dependencies of target OgreMain
[ 41%] Building CXX object Ogre/Sources/OgreMain/CMakeFiles/OgreMain.dir/src/OgreASTCCodec.cpp.o

NMAKE : fatal error U1077: 'D:\NVPACK\android-ndk-r10e\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-g++.exe' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
```

**Comment by arkeon7** [comment] 2018-04-25 14:32
Reverted to the last Ogre version I was used before I tried to update, and all is working correctly. So this is not related to another dependencies. It's definitely a change in Ogre in the past few months ^^

**Comment by paroj** [comment] 2018-04-26 14:04
I just tried latest master (SampleBrowser) which works fine. To me the issue looks like you messed up the headers between compiling Ogre and your application.

Can you reproduce the issue with the vanilla master/ SampleBrowser?

**Comment by arkeon7** [comment] 2018-05-03 07:42
Got the same issue on Linux ^^
I'm loosing my hairs on this :/ I still have no idea why Ogre crash on initialisation...
All is working well on Windows. I've rebuild a large part of my cmake scripts to make sure it's all clean.
Any idea if a compile flag or something have been added or removed in current Ogre cmake scripts ?

**Comment by arkeon7** [comment] 2018-05-03 09:43
interesting : https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSString.h
"using std::string with shared libraries is broken on android when using gnustl
due to the platform-level decision to set _GLIBCXX_FULLY_DYNAMIC_STRING to 0"

**Comment by paroj** [comment] 2018-05-03 12:13
do you compile your code as C++11? Do the tutorial apps compile? (Samples/Tutorials)

**Comment by arkeon7** [comment] 2018-05-16 14:53
Do you see anything in that revision that could fail on my systems ? https://bitbucket.org/sinbad/ogre/commits/9d798ca4fb82308c249ed7a193265782e3e79448?at=default

I've build and run the previous revision without trouble but it seems that revision make the bug.
(I'm not sure yet, building all this ogres revision is long and I can make a mistake)

**Comment by arkeon7** [comment] 2018-05-17 08:42
Finally found what it don't like!

All your changes on constructors with empty strings that call another constructor make it crash like : MovableObject::MovableObject() : MovableObject(BLANKSTRING) {}
If I just revert all this changes on MovableObject, SceneNode and Node all is working correctly!

No idea why it's working on Windows and on your builds but the way it's written seems bad to me.
I'm just glad I finally found what was blocking me for month...

**Comment by paroj** [comment] 2018-05-17 10:17
this is seriously strage. Can you reproduce it with a minimal sample like:

```cpp
#include <string>

using namespace std;

const string BLANK;

struct Test
{
    string mem;
    Test() : Test(BLANK) {}

    Test(const string& s) : mem(s) {}
};

int main() {
    Test t;
    return 0;
}
```

**Comment by arkeon7** [comment] 2018-05-17 10:42
The real problem is the use of BLANKSTRING here... replacing by "" is working.
It's like the static variable was not initialized yet. can it be related to not using precompiled headers ?

**Comment by arkeon7** [comment] 2018-05-17 10:54
Your minimal sample is working on linux. There is no segmentation fault ^^

**Comment by paroj** [comment] 2018-05-17 12:40
maybe it has something to do with this
https://stackoverflow.com/questions/6173872/why-is-multiple-definition-of-a-const-global-variable-allowed-in-c-and-not-in

note that BLANKSTRING is just const, but not static. Maybe making it static will help?

**Comment by arkeon7** [comment] 2018-05-17 14:02
possibly : https://stackoverflow.com/questions/2605520/c-where-to-initialize-static-const

**Comment by paroj** [comment] 2019-12-23 11:28
closing as could not be reproduced

**Closed by paroj** 2019-12-23 11:28 UTC
Labels: incomplete
