### ISSUE TITLE
Build failed 1.12.1 Windows x64

### ISSUE THREAD

**Issue by glennra** [OGRECave/ogre#1182] opened 2019-05-08 22:35 UTC
#### System Information
- Ogre Version: :1.12.1: 
- Operating System / Platform: :Windows 10: 
- RenderSystem: :na:

#### Detailled description
Build error: \ogre-1-12\Components\Overlay\src\OgreFont.cpp(39): fatal error C1083: Cannot open include file: 'ft2build.h': No such file or directory

Excerpt from CMake output - it says freetype  has been found:
-- The following external packages were located on your system.
-- This installation will have the extra features provided by these packages.
+ zlib
+ zziplib
+ freeimage
+ freetype
+ OpenGL
+ OpenGL ES 2.x
+ DirectX9
+ DirectX11
+ cg
+ Python
+ SDL2
-----------------------------------------------------------------------------
-- The following OPTIONAL packages could NOT be located on your system.
-- Consider installing them to enable more features from this software.
+ OpenEXR: Load High dynamic range images <http://www.openexr.com/>
+ Doxygen: Tool for building API documentation <http://doxygen.org>
+ Softimage: Softimage SDK needed for building XSIExporter <FALSE>
-----------------------------------------------------------------------------

**Comment by paroj** [comment] 2019-05-10 00:18
> Excerpt from CMake output - it says freetype has been found:

apparently it did not. Verify that all related paths are correct.

**Comment by glennra** [comment] 2019-05-10 00:22
Which paths? I didn't change anything. I thought it was supposed to include the dependencies automatically.

**Comment by paroj** [comment] 2019-05-10 00:23
notably `FREETYPE_INCLUDE_DIR_ft2build`

**Comment by glennra** [comment] 2019-05-10 00:24
In any case, that's the bug I'm reporting. CMake says freetype has been found, when it has not.

**Comment by glennra** [comment] 2019-05-10 00:38
Started cmake-gui (3.14.0-rc2) again to check that variable and it seemed to be Ok. Reran configure and generate and it's working now. I had run cmake-gui initially as usual - configure, set up red fields, configure again, (no reds) generate.

**Comment by paroj** [comment] 2019-05-10 09:36
> In any case, that's the bug I'm reporting. CMake says freetype has been found, when it has not.

we are using the upstream script here. closing as not a bug in ogre

**Closed by paroj** 2019-05-10 09:36 UTC
