### ISSUE TITLE
RenderTargetTexture with two Screens throws exceptions.

### ISSUE THREAD

**Issue by IQS-Leopold** [OGRECave/ogre#713] opened 2018-03-26 13:51 UTC
#### System Information
- Ogre Version: 1.10.11
- Operating System / Platform: Windows 10 X64 (Fall Creators Update)
- RenderSystem: Direct3D9

#### Detailled description
If you move a rendering window from screen one to screen two and you create a RenderTargetTexture and you call rtt->update(); This will fail with an exception (access violation) no matter if the texture was created in front of the window movement or afterwards.

**Comment by paroj** [comment] 2018-05-02 16:10
please provide a stack-trace for this

**Comment by paroj** [comment] 2018-12-11 22:35
duplicate of #710

**Closed** 2019-01-17 18:31 UTC
Labels: RenderSystem: D3D9, incomplete
