### ISSUE TITLE
Error when building in x64 debug

### ISSUE THREAD

**Issue by Bambofy** [OGRECave/ogre#2598] opened 2022-09-24 18:23 UTC
#### System Information
- Ogre Version: 13.4.4
- Operating System / Platform: Windows
- RenderSystem: N/A

#### Detailled description
When building OGRE in release mode it works perfectly, but in debug mode a large number of errors occur.

#### Error List
[OGRE Debug Build Errors.pdf](https://github.com/OGRECave/ogre/files/9639329/OGRE.Debug.Build.Errors.pdf)

**Comment by paroj** [comment] 2022-09-24 18:53
duplicate of #1303

**Closed by paroj** 2022-09-24 18:53 UTC

**Comment by JanGeykenORGADATA** [comment] 2022-09-28 12:06
As a workaround it helps if you open the solutions for pugixml and assimp, set them to debug and rebuild the "Install" project.
After that you can try to build Ogre again.

It should at least work for pugixml, I dissabled assimp in my project because it created some build problems and I can't remeber if the problems there only on the build server
