### ISSUE TITLE
The i386 architecture is deprecated

### ISSUE THREAD

**Issue by crookedbard** [OGRECave/ogre#800] opened 2018-07-04 09:18 UTC
#### System Information
- Ogre Version: :grey_question: 1-11-2
- Operating System / Platform: :grey_question: macOS Mojave 10.14
- RenderSystem: :grey_question: openGL

#### Detailled description
I am trying to build any project of Ogre and I get many errors:
Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'install')

#### Ogre.log
cmake --build . --config Release --target install
2018-07-04 12:15:05.818 xcodebuild[55821:5540996] warning: file type '::com.apple.instruments.instrdst' is based on missing file type 'default::com.apple.package'
note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgreGLSupport')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgreMain')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'RenderSystem_GL')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'Plugin_OctreeSceneManager')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'Plugin_BSPSceneManager')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'ZERO_CHECK')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'Codec_FreeImage')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'RenderSystem_GL3Plus')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'Codec_STBI')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'Plugin_ParticleFX')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'Plugin_PCZSceneManager')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgreOverlay')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgreBites')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'Plugin_OctreeZone')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgreMeshLodGenerator')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgrePaging')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgreRTShaderSystem')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgreTerrain')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgreVolume')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'DefaultSamples')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'SampleBrowser')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgreXMLConverter')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgreHLMS')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgreMeshUpgrader')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'VRMLConverter')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'ALL_BUILD')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'install')

Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'OgreProperty')

** BUILD FAILED **

**Comment by paroj** [comment] 2018-07-04 09:55
duplicate of #801

**Closed by paroj** 2018-07-04 09:55 UTC
