### ISSUE TITLE
Build failure on macOS 10.14 Xcode 10.2 

### ISSUE THREAD

**Issue by glennra** [OGRECave/ogre#1144] opened 2019-03-26 21:57 UTC
#### System Information
- Ogre Version: :1.11.6: 
- Operating System / Platform: :macOS 10.14.3: 
- RenderSystem: :grey_question:

#### Detailled description
OgreMain builds without errors but anything trying to link to it has errors like this:

Ld /Users/glenn/rp/ogre-1-11-build/bin/Debug/VRMLConverter normal x86_64 (in target: VRMLConverter)
    cd /Users/glenn/rp/src/InRow/dep/ogre-1-11
    export MACOSX_DEPLOYMENT_TARGET=10.14
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -L/Users/glenn/rp/ogre-1-11-build/bin/Debug -F/Users/glenn/rp/ogre-1-11-build/bin/Debug -filelist /Users/glenn/rp/ogre-1-11-build/Tools/VRMLConverter/OGRE.build/Debug/VRMLConverter.build/Objects-normal/x86_64/VRMLConverter.LinkFileList -mmacosx-version-min=10.14 -Xlinker -object_path_lto -Xlinker /Users/glenn/rp/ogre-1-11-build/Tools/VRMLConverter/OGRE.build/Debug/VRMLConverter.build/Objects-normal/x86_64/VRMLConverter_lto.o -Xlinker -no_deduplicate -stdlib=libc++ -framework Carbon -framework Cocoa -Wl,-search_paths_first -Wl,-headerpad_max_install_names /Users/glenn/rp/ogre-1-11-build/lib/macosx/Debug/Ogre.framework/Versions/1.11.6/Ogre -Xlinker -dependency_info -Xlinker /Users/glenn/rp/ogre-1-11-build/Tools/VRMLConverter/OGRE.build/Debug/VRMLConverter.build/Objects-normal/x86_64/VRMLConverter_dependency_info.dat -o /Users/glenn/rp/ogre-1-11-build/bin/Debug/VRMLConverter

Undefined symbols for architecture x86_64:
  "Ogre::LogManager::logMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Ogre::LogMessageLevel, bool)", referenced from:
      _main in VRML2mesh.o
      Ogre::LogManager::logMessage(Ogre::LogMessageLevel, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) in VRML2mesh.o
      parseShape(Ogre::Mesh*, vrmllib::Shape const*, Ogre::Matrix4) in VRML2mesh.o
      parseMaterial(vrmllib::Appearance const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in VRML2mesh.o
  "Ogre::LogManager::logWarning(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)", referenced from:
      parseShape(Ogre::Mesh*, vrmllib::Shape const*, Ogre::Matrix4) in VRML2mesh.o
  "Ogre::LogManager::getSingleton()", referenced from:
      parseShape(Ogre::Mesh*, vrmllib::Shape const*, Ogre::Matrix4) in VRML2mesh.o
      parseMaterial(vrmllib::Appearance const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in VRML2mesh.o
  "Ogre::LogManager::createLog(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, bool)", referenced from:
      _main in VRML2mesh.o

The linker errors always seem to involve std::__1::basic_string<char, std::__1::char_traits<char> so it looks to me like a libc++ compatibility issue, however the compile commands all have -stdlib=libc++ .

**Comment by paroj** [comment] 2019-03-26 22:04
duplicate of #894. Its trying to link x86_64 against i386

**Closed by paroj** 2019-03-26 22:04 UTC

**Comment by glennra** [comment] 2019-03-26 22:24
>  Its trying to link x86_64 against i386
I've set CMAKE_OSX_ARCHITECTURES to x86_64 and the ld commands all have `-arch x86_64`. I don't see any evidence of that.

**Comment by paroj** [comment] 2019-03-26 23:50
it is imperative which `-arch` is specified during compilation. Did you pass CMAKE_OSX_ARCHITECTURES before configure? You must invoke cmake via command line instead of using the gui for this. If not, try again with a clean build folder.

Meanwhile I am tracking a 10.14 build here: #1145

**Comment by paroj** [comment] 2019-03-27 00:05
also try enabling GL3+ enabled (yeah the build scripts are arcane)

**Comment by glennra** [comment] 2019-03-27 21:05
It builds using the makefile generator. The issue must be with Xcode.
