### ISSUE TITLE
Using mingw to build ogreV1.11.2. after building sdk, running python sample, Exception occurs

### ISSUE THREAD

**Issue by niubaty** [OGRECave/ogre#839] opened 2018-08-14 04:56 UTC
Using mingw to build ogreV1.11.2. after building sdk, running python sample, Exception occurs
Building **ogreV1.10.12, python sample runs all right.**
Using vs14 building ogreV1.11.2 without python binding, all samples run all right
Using vs14 building ogreV1.11.2 with python binding, vs14 report compiling errors when building python binding. I do not know how to solve the python binding problems, so I have to choose mingw.

#### System Information
- Ogre Version: :  1_11_2
- Operating System / Platform:  windows10 64bit (win7 64bit has same problem) 
- RenderSystem: :  openGL
- building tool::  x86_64-8.1.0-release-posix-seh-rt_v6-rev0

#### Detailled description
F:\ogre_build\br_mingw2\sdk\bin>**python bites_sample.py**
Creating resource group General
Creating resource group OgreInternal
Creating resource group OgreAutodetect
SceneManagerFactory for type 'DefaultSceneManager' registered.
Registering ResourceManager for type Material
Registering ResourceManager for type Mesh
Registering ResourceManager for type Skeleton
MovableObjectFactory for type 'ParticleSystem' registered.
ArchiveFactory for archive type FileSystem registered.
ArchiveFactory for archive type Zip registered.
ArchiveFactory for archive type EmbeddedZip registered.
DDS codec registering
ETC codec registering
Registering ResourceManager for type HighLevelGpuProgram
Registering ResourceManager for type Compositor
MovableObjectFactory for type 'Entity' registered.
MovableObjectFactory for type 'Light' registered.
MovableObjectFactory for type 'BillboardSet' registered.
MovableObjectFactory for type 'ManualObject' registered.
MovableObjectFactory for type 'BillboardChain' registered.
MovableObjectFactory for type 'RibbonTrail' registered.
Loading library .\RenderSystem_GL
Installing plugin: GL RenderSystem
OpenGL Rendering Subsystem created.
Plugin successfully installed
Loading library .\RenderSystem_GL3Plus
Installing plugin: GL 3+ RenderSystem
OpenGL 3+ Rendering Subsystem created.
Plugin successfully installed
Loading library .\Plugin_ParticleFX
Installing plugin: ParticleFX
Particle Emitter Type 'Point' registered
Particle Emitter Type 'Box' registered
Particle Emitter Type 'Ellipsoid' registered
Particle Emitter Type 'Cylinder' registered
Particle Emitter Type 'Ring' registered
Particle Emitter Type 'HollowEllipsoid' registered
Particle Affector Type 'LinearForce' registered
Particle Affector Type 'ColourFader' registered
Particle Affector Type 'ColourFader2' registered
Particle Affector Type 'ColourImage' registered
Particle Affector Type 'ColourInterpolator' registered
Particle Affector Type 'Scaler' registered
Particle Affector Type 'Rotator' registered
Particle Affector Type 'DirectionRandomiser' registered
Particle Affector Type 'DeflectorPlane' registered
Plugin successfully installed
Loading library .\Plugin_BSPSceneManager
Installing plugin: BSP Scene Manager
Plugin successfully installed
Loading library .\Codec_STBI
stb_image - v2.19 - public domain JPEG/PNG reader
Supported formats: jpeg,jpg,png,bmp,psd,tga,gif,pic,ppm,pgm,hdr
Loading library .\Plugin_PCZSceneManager
Installing plugin: Portal Connected Zone Scene Manager
PCZone Factory Type 'ZoneType_Default' registered
Plugin successfully installed
Loading library .\Plugin_OctreeZone
Installing plugin: Octree Zone Factory
Plugin successfully installed
Loading library .\Plugin_OctreeSceneManager
Installing plugin: Octree Scene Manager
Plugin successfully installed
*-*-* OGRE Initialising
*-*-* Version 1.11.2 (Rhagorthua)
OverlayElementFactory for type Panel registered.
OverlayElementFactory for type BorderPanel registered.
OverlayElementFactory for type TextArea registered.
Registering ResourceManager for type Font
Traceback (most recent call last):
  File "bites_sample.py", line 90, in <module>
    app.initApp()
**RuntimeError: FileNotFoundException:** 指定的映像文件不包含资源区域。
 **in ConfigDialog::display**

**Comment by paroj** [comment] 2019-01-25 13:15
duplicate of #1064

**Closed by paroj** 2019-01-25 13:15 UTC
Labels: Platform: MinGW
