### ISSUE TITLE
ogre3d 1.11.5 compile failed

### ISSUE THREAD

**Issue by beew** [OGRECave/ogre#1116] opened 2019-03-02 21:47 UTC
- Ogre Version: 1.11.5
- Operating System / Platform: Ubuntu16.0.4 

Tried to compile, run cmake and it failed with
```
Scanning dependencies of target libzzip
[  9%] Building C object zzip/CMakeFiles/libzzip.dir/dir.c.o
In file included from /home/bernard/Downloads/ogre-1.11.5/build/zziplib-develop/zzip/dir.c:9:0:
/home/bernard/Downloads/ogre-1.11.5/build/zziplib-develop/zzip/lib.h:29:5: error: unknown type name ‘uint32_t’
     uint32_t    d_usize;        /* uncompressed size */
     ^
/home/bernard/Downloads/ogre-1.11.5/build/zziplib-develop/zzip/lib.h:30:5: error: unknown type name ‘uint32_t’
     uint32_t    d_csize;        /* compressed size */
     ^
/home/bernard/Downloads/ogre-1.11.5/build/zziplib-develop/zzip/lib.h:31:5: error: unknown type name ‘uint32_t’
     uint32_t    d_crc32;        /* the adler32-checksum */
     ^
/home/bernard/Downloads/ogre-1.11.5/build/zziplib-develop/zzip/lib.h:32:5: error: unknown type name ‘uint32_t’
     uint32_t    d_off;          /* offset of file in zipfile */
     ^
/home/bernard/Downloads/ogre-1.11.5/build/zziplib-develop/zzip/lib.h:33:5: error: unknown type name ‘uint16_t’
     uint16_t    d_reclen;       /* next dir_hdr structure offset */
     ^
/home/bernard/Downloads/ogre-1.11.5/build/zziplib-develop/zzip/lib.h:34:5: error: unknown type name ‘uint16_t’
     uint16_t    d_namlen;       /* explicit namelen of d_name */
     ^
/home/bernard/Downloads/ogre-1.11.5/build/zziplib-develop/zzip/lib.h:35:5: error: unknown type name ‘uint8_t’
     uint8_t     d_compr;        /* the compression type, 0 = store, 8 = inflate */
     ^
zzip/CMakeFiles/libzzip.dir/build.make:62: recipe for target 'zzip/CMakeFiles/libzzip.dir/dir.c.o' failed
make[2]: *** [zzip/CMakeFiles/libzzip.dir/dir.c.o] Error 1
CMakeFiles/Makefile2:87: recipe for target 'zzip/CMakeFiles/libzzip.dir/all' failed
make[1]: *** [zzip/CMakeFiles/libzzip.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Tried running cmake on ogre3d1.10.2,  zzip configured successfully with no issue. so it seems this is peculiar to v 1.11.5 and not my setup.

**Comment by paroj** [comment] 2019-03-02 22:58
works fine here: https://travis-ci.org/OGRECave/ogre/jobs/500911915

**Comment by beew** [comment] 2019-03-03 00:50
I got the same errors in configure that I posted in OP for source codes from master as in your screenshot, but it compiled and launched successfully nevertheless. So I suppose it works despite those zzlib errors

However build failed for 1.11.5 with errors which seems unrelated to OP
```
/home/bernard/Downloads/ogre-1.11.5/build/Components/Python/OgrePYTHON_wrap.cxx:399427:144: error: call of overloaded ‘createOrRetrieve(const String&, const String&, bool&, Ogre::ManualResourceLoader*&, const NameValuePairList*)’ is ambiguous
       result = (arg1)->createOrRetrieve((Ogre::String const &)*arg2,(Ogre::String const &)*arg3,arg4,arg5,(Ogre::NameValuePairList const *)arg6);
                                                                                                                                                ^
In file included from /home/bernard/Downloads/ogre-1.11.5/OgreMain/include/Ogre.h:83:0,
                 from /home/bernard/Downloads/ogre-1.11.5/build/Components/Python/OgrePYTHON_wrap.cxx:5088:
/home/bernard/Downloads/ogre-1.11.5/OgreMain/include/OgreMeshManager.h:98:40: note: candidate: Ogre::ResourceManager::ResourceCreateOrRetrieveResult Ogre::MeshManager::createOrRetrieve(const String&, const String&, bool, Ogre::ManualResourceLoader*, const NameValuePairList*, Ogre::HardwareBuffer::Usage, Ogre::HardwareBuffer::Usage, bool, bool)
         ResourceCreateOrRetrieveResult createOrRetrieve(
                                        ^
In file included from /home/bernard/Downloads/ogre-1.11.5/OgreMain/include/OgreCompositorManager.h:32:0,
                 from /home/bernard/Downloads/ogre-1.11.5/OgreMain/include/Ogre.h:46,
                 from /home/bernard/Downloads/ogre-1.11.5/build/Components/Python/OgrePYTHON_wrap.cxx:5088:
/home/bernard/Downloads/ogre-1.11.5/OgreMain/include/OgreResourceManager.h:140:40: note: candidate: Ogre::ResourceManager::ResourceCreateOrRetrieveResult Ogre::ResourceManager::createOrRetrieve(const String&, const String&, bool, Ogre::ManualResourceLoader*, const NameValuePairList*)
         ResourceCreateOrRetrieveResult createOrRetrieve(const String& name,
                                        ^
/home/bernard/Downloads/ogre-1.11.5/build/Components/Python/OgrePYTHON_wrap.cxx: In function ‘PyObject* _wrap_MeshManager_createOrRetrieve__SWIG_5(PyObject*, PyObject*)’:
/home/bernard/Downloads/ogre-1.11.5/build/Components/Python/OgrePYTHON_wrap.cxx:400199:144: error: call of overloaded ‘createOrRetrieve(const String&, const String&, bool&, Ogre::ManualResourceLoader*&, const NameValuePairList*)’ is ambiguous
       result = (arg1)->createOrRetrieve((Ogre::String const &)*arg2,(Ogre::String const &)*arg3,arg4,arg5,(Ogre::NameValuePairList const *)arg6);
                                                                                                                                                ^
In file included from /home/bernard/Downloads/ogre-1.11.5/OgreMain/include/Ogre.h:83:0,
                 from /home/bernard/Downloads/ogre-1.11.5/build/Components/Python/OgrePYTHON_wrap.cxx:5088:
/home/bernard/Downloads/ogre-1.11.5/OgreMain/include/OgreMeshManager.h:98:40: note: candidate: Ogre::ResourceManager::ResourceCreateOrRetrieveResult Ogre::MeshManager::createOrRetrieve(const String&, const String&, bool, Ogre::ManualResourceLoader*, const NameValuePairList*, Ogre::HardwareBuffer::Usage, Ogre::HardwareBuffer::Usage, bool, bool)
         ResourceCreateOrRetrieveResult createOrRetrieve(
                                        ^
In file included from /home/bernard/Downloads/ogre-1.11.5/OgreMain/include/OgreCompositorManager.h:32:0,
                 from /home/bernard/Downloads/ogre-1.11.5/OgreMain/include/Ogre.h:46,
                 from /home/bernard/Downloads/ogre-1.11.5/build/Components/Python/OgrePYTHON_wrap.cxx:5088:
/home/bernard/Downloads/ogre-1.11.5/OgreMain/include/OgreResourceManager.h:140:40: note: candidate: Ogre::ResourceManager::ResourceCreateOrRetrieveResult Ogre::ResourceManager::createOrRetrieve(const String&, const String&, bool, Ogre::ManualResourceLoader*, const NameValuePairList*)
         ResourceCreateOrRetrieveResult createOrRetrieve(const String& name,
                                        ^
Components/Python/CMakeFiles/_Ogre.dir/build.make:70: recipe for target 'Components/Python/CMakeFiles/_Ogre.dir/OgrePYTHON_wrap.cxx.o' failed
make[2]: *** [Components/Python/CMakeFiles/_Ogre.dir/OgrePYTHON_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:1758: recipe for target 'Components/Python/CMakeFiles/_Ogre.dir/all' failed
make[1]: *** [Components/Python/CMakeFiles/_Ogre.dir/all] Error 2
[100%] Linking CXX shared module ../../java/libs/libOgreJNI.so
[100%] Built target OgreJNI
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by beew** [comment] 2019-03-03 02:40
So it seems that the zzlib error was introduced in 1.11.5, which was absent in 1.114. But build failed because of the errors in my second post above. These errors are present since 1.11.2 and is gone only in master.

**Comment by beew** [comment] 2019-03-03 03:07
This is 11.1.5

The libzzip errors go away if compile with opton  ref:  https://github.com/OGRECave/ogre/issues/1071
```
-DOGRE_BUILD_DEPENDENCIES=OFF
```

But build still fails with errors
```
 error: call of overloaded ‘createOrRetrieve(const String&, const String&, bool&, Ogre::ManualResourceLoader*&, const NameValuePairList*)’ is ambiguous
```
and a bunch of others like that.

**Comment by paroj** [comment] 2019-03-03 11:47
duplicate of #1092, fixed in master

**Closed by paroj** 2019-03-03 11:47 UTC
