### ISSUE TITLE
No way to quit the application. 

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [OGRECave/ogre#689] opened 2018-03-07 14:08 UTC
#### Expected behavior
I downloaded this app from f-droid  and opened this for a while. Then I want to close the app. 

#### Actual behavior 

When I opened the app for some time now i want to close the app by "quit"option fixed in app. 
No way to quit the app. 

#### How to reproduce
Download the OgerSampleBrowser from f-droid. 
Then open it for some time, 
when u want to close the app, press on the "quit" option mentioned in app. 
It doesn't gets quit. 

* Browser: OgerSampleBrowser 
*Version:1.10.11
* Operating system:5.1.1

#### Recording Of The Bug

Here is the GIF of the bug. 
![20180304_184531.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520170277/smw67oicyv7477amvrnt.gif)

    
OgreSampleBrowser (Object-Oriented Graphics Rendering Engine - Samples) - https://f-droid.org/app/org.ogre.browser

**Comment by paroj** [comment] 2018-03-07 15:06
duplicate of #686

**Closed by paroj** 2018-03-07 15:06 UTC
