### ISSUE TITLE
Exception when running SampleBrowser on PC

### ISSUE THREAD

**Issue by raynaudoe** [OGRECave/ogre#777] opened 2018-06-01 13:12 UTC
- Ogre Version: 1.10.12 
- Operating System / Platform: Linux PC 
- RenderSystem: GLES2

Running SampleBrowser after a fresh compilation crashes when selecting gles2 as RS, throwing this error:

> Registering ResourceManager for type Texture
GLES2RenderSystem::_createRenderWindow "OGRE Sample Browser", 640x480 windowed  miscParams: FSAA=1 gamma=No parentWindowHandle=81788934 vsync=No 
OpenGL Warning: glXChooseVisual: bad attrib=0x20b2, ignoring
Actual frame buffer FSAA: 1, gamma: 0, colourBufferSize: 32
An exception has occurred: RuntimeAssertionException: glXCreateContextAttribsARB() function not found in createNewContext at /home/ubuntu/Projects/RenderSystems/GLSupport/src/GLX/OgreGLXGLSupport.cpp (line 859)

#### Ogre.log
```
Creating resource group General
Creating resource group Internal
Creating resource group Autodetect
SceneManagerFactory for type 'DefaultSceneManager' registered.
Registering ResourceManager for type Material
Registering ResourceManager for type Mesh
Registering ResourceManager for type Skeleton
MovableObjectFactory for type 'ParticleSystem' registered.
ArchiveFactory for archive type FileSystem registered.
ArchiveFactory for archive type Zip registered.
ArchiveFactory for archive type EmbeddedZip registered.
DDS codec registering
PVRTC codec registering
ETC codec registering
stb_image - v2.15 - public domain JPEG/PNG reader
Supported formats: jpeg,jpg,png,bmp,psd,tga,gif,pic,ppm,pgm,hdr
Registering ResourceManager for type HighLevelGpuProgram
Registering ResourceManager for type Compositor
MovableObjectFactory for type 'Entity' registered.
MovableObjectFactory for type 'Light' registered.
MovableObjectFactory for type 'BillboardSet' registered.
MovableObjectFactory for type 'ManualObject' registered.
MovableObjectFactory for type 'BillboardChain' registered.
MovableObjectFactory for type 'RibbonTrail' registered.
Loading library /home/ubuntu/Projects/output/lib/RenderSystem_GL
Installing plugin: GL RenderSystem
OpenGL Rendering Subsystem created.
Plugin successfully installed
Loading library /home/ubuntu/Projects/output/lib/RenderSystem_GLES2
Installing plugin: OpenGL ES 2.0 RenderSystem
OpenGL ES 2.x Rendering Subsystem created.
Plugin successfully installed
Loading library /home/ubuntu/Projects/output/lib/Plugin_ParticleFX
Installing plugin: ParticleFX
Particle Emitter Type 'Point' registered
Particle Emitter Type 'Box' registered
Particle Emitter Type 'Ellipsoid' registered
Particle Emitter Type 'Cylinder' registered
Particle Emitter Type 'Ring' registered
Particle Emitter Type 'HollowEllipsoid' registered
Particle Affector Type 'LinearForce' registered
Particle Affector Type 'ColourFader' registered
Particle Affector Type 'ColourFader2' registered
Particle Affector Type 'ColourImage' registered
Particle Affector Type 'ColourInterpolator' registered
Particle Affector Type 'Scaler' registered
Particle Affector Type 'Rotator' registered
Particle Affector Type 'DirectionRandomiser' registered
Particle Affector Type 'DeflectorPlane' registered
Plugin successfully installed
Loading library /home/ubuntu/Projects/output/lib/Plugin_BSPSceneManager
Installing plugin: BSP Scene Manager
Plugin successfully installed
Loading library /home/ubuntu/Projects/output/lib/Plugin_CgProgramManager
Installing plugin: Cg Program Manager
Plugin successfully installed
Loading library /home/ubuntu/Projects/output/lib/Plugin_PCZSceneManager
Installing plugin: Portal Connected Zone Scene Manager
PCZone Factory Type 'ZoneType_Default' registered
Plugin successfully installed
Loading library /home/ubuntu/Projects/output/lib/Plugin_OctreeZone
Installing plugin: Octree Zone Factory
Plugin successfully installed
Loading library /home/ubuntu/Projects/output/lib/Plugin_OctreeSceneManager
Installing plugin: Octree Scene Manager
Plugin successfully installed
*-*-* OGRE Initialising
*-*-* Version 1.10.12 (Xalafu)
OverlayElementFactory for type Panel registered.
OverlayElementFactory for type BorderPanel registered.
OverlayElementFactory for type TextArea registered.
Registering ResourceManager for type Font
CPU Identifier & Features
-------------------------
 *   CPU ID: GenuineIntel: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
 *          SSE: yes
 *         SSE2: yes
 *         SSE3: yes
 *        SSE41: yes
 *        SSE42: yes
 *          MMX: yes
 *       MMXEXT: yes
 *        3DNOW: no
 *     3DNOWEXT: no
 *         CMOV: yes
 *          TSC: yes
 *INVARIANT TSC: yes
 *          FPU: yes
 *          PRO: yes
 *           HT: no
-------------------------
******************************
*** Starting GLX Subsystem ***
******************************
GLX_VERSION = 1.3 Chromium
GLX_EXTENSIONS = GLX_ARB_multisample GLX_EXT_texture_from_pixmap GLX_SGIX_fbconfig GLX_ARB_get_proc_address
Registering ResourceManager for type Texture
GLES2RenderSystem::_createRenderWindow "OGRE Sample Browser", 640x480 windowed  miscParams: FSAA=1 gamma=No parentWindowHandle=81788934 vsync=No 
OpenGL Warning: glXChooseVisual: bad attrib=0x20b2, ignoring
Actual frame buffer FSAA: 1, gamma: 0, colourBufferSize: 32
An exception has occurred: RuntimeAssertionException: glXCreateContextAttribsARB() function not found in createNewContext at /home/ubuntu/Projects/RenderSystems/GLSupport/src/GLX/OgreGLXGLSupport.cpp (line 859)

```

**Comment by paroj** [comment] 2018-06-01 14:37
duplicate of #766

**Closed by paroj** 2018-06-01 14:37 UTC
