### ISSUE TITLE
Quaternion should be double precision when Ogre is compiled with double precision

### ISSUE THREAD

**Issue by BobFlow** [OGRECave/ogre#2733] opened 2023-01-09 08:49 UTC
#### System Information
- Ogre Version: 1.12.10 - 13.4
- Operating System / Platform: All
- RenderSystem: All

#### Detailed description

OgreQuaternion storage has been forced to float when compiled with the flag OGRE_CONFIG_DOUBLE. The issue has been introduced with this commit: https://github.com/OGRECave/ogre/commit/45f2531138902414072cbba551b77b11aebb692d
We recently upgraded to the latest version of Ogre. Having quaternions stored in float instead of double led to some numerical stability issues in our project. The fix is reverting the file OgreQuaternion.cpp/h.

**Comment by paroj** [comment] 2023-01-09 12:30
I dont think that float storage is the problem as the Quaternion elements should always be in the range -1..1, where float is sufficient.
The issue is likely that some operations are now only done in float precision too. This one comes to my mind:
https://github.com/OGRECave/ogre/blob/5a8a0c1164c7a455364656cf1e6d3ec478e6b55c/OgreMain/src/OgreQuaternion.cpp#L260-L272

can you do `Real(w), Real(x)` etc. to force all computations to double?

Also, do you have a example expression which produces incorrect results with float? We could use that to narrow down the issue and use it as a regression test later.

**Comment by BobFlow** [comment] 2023-01-10 16:06
Hi Paroj. Thanks for the super quick reply!

Indeed, internal float operations are a problem. However, also the storage itself is a problem in our case.

Please consider the following example:
```c++
    Ogre::Quaternion rot( Ogre::Degree( 180 ), Ogre::Vector3::UNIT_Z );
    Ogre::Quaternion rot_inv = rot.Inverse();
    Ogre::Vector3    v_s( 1e6, 1e6, 0 );
    Ogre::Vector3    v_e = rot * v_s;
    v_e = rot_inv * v_e;
    std::cout << ( v_s - v_e ).length() << std::endl;
```

The output is 7.17214e-08 with double and 0.337175 with floats.
Since we use georeferenced data, it is not unusual to have input vectors with 1e6 that are then transformed into rendering coordinates.

**Comment by paroj** [comment] 2023-01-10 19:43
that gives me `1.0783980504722104e-08` for both float and double Quaternion on current master (Linux, Clang).

Indeed, looking at the implementation of `operator*`, all operation related to the vector are done as double.

**Comment by BobFlow** [comment] 2023-01-11 10:51
I'm sorry, I mixed up the quick tests yesterday. You are right; I got the same results as you with the code above. 
This is because axis/angle Ogre::Degree( 180 ), Ogre::Vector3::UNIT_Z is quite a special case. However, using Ogre::Degree( 90 ), it's already quite different. 

Using the code:
```c++
    Ogre::Quaternion rot( Ogre::Degree( 90 ), Ogre::Vector3::UNIT_Z );
    Ogre::Quaternion rot_inv = rot.Inverse();
    Ogre::Vector3    v_s( 1e6, 1e6, 0 );
    Ogre::Vector3    v_e = rot * v_s;
    v_e = rot_inv * v_e;
    std::cout << ( v_s - v_e ).length() << std::endl;
```

I obtained 0.277301 with float storage and 0.0968129 with forced double storage. I'm using ogre 13.5.3 with Visual Studio 2022, compiled with the OGRE_CONFIG_DOUBLE flag. 

It makes sense to me. Even if the operations are performed in double, and it's a simple multiplication, the quaternion itself loses numerical precision with the storage. Checking the stored value for the quaternion "rot_inv" I get respectively for float-double:
```c++
		w	0.707106829	float
		x	-0.00000000	float
		y	-0.00000000	float
		z	-0.707106829	float
		w	0.70710679328816484	double
		x	-0.0000000000000000	double
		y	-0.0000000000000000	double
		z	-0.70710679328816484	double
```

If I set v_e to 1e07 and 1e08, the final error increase to 2.77301 and 27.7301 for float and 0.968129 and 9.68129 for double. Thanks!

**Comment by paroj** [comment] 2023-01-11 12:44
the culprit in your example is not float storage, but rather float operations in:
https://github.com/OGRECave/ogre/blob/c26d55098df5df7bd2721d904d15f8d86291b9a0/OgreMain/src/OgreQuaternion.cpp#L274-L276

If you force them to double as:
```cpp
Real fNorm = Real(w)*w+Real(x)*x+Real(y)*y+Real(z)*z;
```

you get the same error with float storage. Will push a fix later.

**Comment by BobFlow** [comment] 2023-01-11 16:48
Awesome! I noticed there are many functions involving float multiplication in the quaternion class, e.g.
Operators, FromAngleAxis, ToAngleAxis, ToRotationMatrix, x/y/z/axis, inverse, exp/log.

Imho, it would be easier to revert and keep the storage as double. If you prefer not to keep the storage as float, in the next few days, I can try manually performing the cast internally or wait for the commit to see if it solves the couple of problems I've noticed in our project. Many thanks!

**Comment by paroj** [comment] 2023-01-11 23:59
committed e1f7db66368c5b6fc452f52f4a8c57fe23fdbdb2

feel free to add further cast and extend the test.

Fixing the storage to float is preferable as it eases reasoning about the code. In the end everything we send to the GPU is float, so we should make it clear as early as possible (related #730). Also it halves the amount of memory - which adds up as each Node contains 3 Quaternions.

**Comment by BobFlow** [comment] 2023-01-12 11:13
Unfortunately, the fix and explicit converting to double the internal operations don't work. It's difficult to trace in our project where the numerical approximation of float causes issues, so I tried to make a very simple example. It's a gizmo tool with several scene nodes used and several transformations and decomposition involved. Translation and scaling work fine with georeferenced (big coordinates) input data, but rotation is shaking. Everything works fine if we use double storage for quaternions as it used to. I've tried to make the explicit double conversion in the class for each operation. However, I'm still convinced that the storage and the functions should be double when I explicitly choose to compile ogre with the double flag.
I'm attaching the updated quaternion.h/cpp with the forced (Real=double) casts at each operation I've tried to use, although the only solution for us is to revert the commit and keep the storage as double.
Thanks

[OgreQuaternion.zip](https://github.com/OGRECave/ogre/files/10400915/OgreQuaternion.zip)

**Comment by paroj** [comment] 2023-01-12 11:29
could you upload a video sequence of the "shaking"?

**Comment by BobFlow** [comment] 2023-01-12 11:43
Here it is
https://user-images.githubusercontent.com/8436572/212058079-c48bcf7e-7f30-47d6-a7d6-dd016734e961.mp4

**Comment by paroj** [comment] 2023-01-12 13:51
you are merely rotating around the object center. This kind of rotation should definitely work with floats.

My next guess would be that you feed some unnormalized axis into `FromAngleAxis`, where precision wrecked on storage where normalise cannot save us.

While I agree that just reverting to double storage is easier, it would merely mask some underlying bugs related to this.

**Comment by BobFlow** [comment] 2023-01-12 16:18
I did some further tests to track down the issue, and I made a minimal sample with real data:
```c++
    Ogre::Affine3 t1(Ogre::Vector3(538160.17723690509, 5604959.8361441437, 17.693394674919546), Ogre::Quaternion(), Ogre::Vector3(1, 1, 1));
    Ogre::Matrix3 rot;
    rot.FromEulerAnglesXYZ(Ogre::Radian(5), Ogre::Radian(0), Ogre::Radian(0));

    Ogre::Quaternion q;
    q.FromRotationMatrix(rot);
    std::cout << std::setprecision(16) << q << std::endl;

    Ogre::Affine3 t2(Ogre::Vector3(0, 0, 0), q, Ogre::Vector3(1, 1, 1));
    Ogre::Affine3 tf = (t2 * t1.inverse());
    std::cout << std::setprecision(16) << tf.getTrans() << std::endl;
```

I get the following output:
_double storage:_ 
Quaternion(0.8011436546367802, -0.5984721088346192, 0, 0)
Vector3(-538160.1772369051, -1589932.596411323, 5374726.971943664)
_float storage:_
Quaternion(0.8011436462402344, -0.5984721183776855, 0, 0)
Vector3(-538160.1772369051, -1589932.468365905, 5374727.001317068)

As you can see, the quaternion is normalized and quite similar. However, the composition with real-world double transformations is quite different, and I get substantial approximations in the translation part of the matrix that could explain the "shaking".

Unless I'm missing something, all the operations are performed in double, even with float storage in my version. For reference, here's the modified from/to rotation matrix function I'm using with the float storage (the same as the .zip attached before):

```c++

    void Quaternion::FromRotationMatrix (const Matrix3& kRot)
    {
        // Algorithm in Ken Shoemake's article in 1987 SIGGRAPH course notes
        // article "Quaternion Calculus and Fast Animation".

        Real fTrace = kRot[0][0]+kRot[1][1]+kRot[2][2];
        Real fRoot;

        if ( fTrace > 0.0 )
        {
            // |w| > 1/2, may as well choose w > 1/2
            fRoot = Math::Sqrt(fTrace + 1.0f);  // 2w
            w = 0.5f*fRoot;
            fRoot = 0.5f/fRoot;  // 1/(4w)
            x = (kRot[2][1]-kRot[1][2])*fRoot;
            y = (kRot[0][2]-kRot[2][0])*fRoot;
            z = (kRot[1][0]-kRot[0][1])*fRoot;
        }
        else { .... omissis not relevant }
}

    void Quaternion::ToRotationMatrix (Matrix3& kRot) const
    {
        Real fTx  = (Real)x+x;
        Real fTy  = (Real)y+y;
        Real fTz  = (Real)z+z;
        Real fTwx = fTx*w;
        Real fTwy = fTy*w;
        Real fTwz = fTz*w;
        Real fTxx = fTx*x;
        Real fTxy = fTy*x;
        Real fTxz = fTz*x;
        Real fTyy = fTy*y;
        Real fTyz = fTz*y;
        Real fTzz = fTz*z;

        kRot[0][0] = 1.0f-(fTyy+fTzz);
        kRot[0][1] = fTxy-fTwz;
        kRot[0][2] = fTxz+fTwy;
        kRot[1][0] = fTxy+fTwz;
        kRot[1][1] = 1.0f-(fTxx+fTzz);
        kRot[1][2] = fTyz-fTwx;
        kRot[2][0] = fTxz-fTwy;
        kRot[2][1] = fTyz+fTwx;
        kRot[2][2] = 1.0f-(fTxx+fTyy);
    }

```

**Comment by paroj** [comment] 2023-01-12 17:52
ok, this boils down to
```
sin(1e-7)*5e6 = 0.5
```
where `1e-7` is the error introduced by float (stores only 6 decimal places) and `5e6` is your largest translation vector.

If your units are meters, then this probably explains the shaking at rotation and in turn means we have to revert..

**Closed** 2023-01-13 00:38 UTC
